apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-dashboard-configmap
data:
  REACT_APP_APP_DOMAIN: 'https://infra-dashboard.adeptmind.net'
  REACT_APP_API_DOMAIN: 'https://infra-onboarding-api.adeptmind.net'
