---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-rollout-gateway
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - dashboard.infra.adeptmind.net
    - infra-dashboard.adeptmind.net
  - port:
      name: https
      number: 443
      protocol: HTTP
    hosts:
    - infra-dashboard.adeptmind.net
