apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-dashboard-configmap
data:
  REACT_APP_API_DOMAIN: http://api.on-boarding.retail.adeptmind.net
  REACT_APP_APP_DOMAIN: http://dashboard.retail.adeptmind.net
