# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     acme.cert-manager.io/http01-edit-in-place: "true"
#     kubernetes.io/ingress.class: haproxy
#     cert-manager.io/cluster-issuer: letsencrypt
#   finalizers:
#   - networking.gke.io/ingress-finalizer-V2
#   name: infra-dashboard-ingress
# spec:
#   rules:
#   - host: dashboard.infra.adeptmind.net
#     http:
#       paths:
#       - backend:
#           service:
#             name: infra-dashboard-svc
#             port:
#               number: 9090
#         pathType: ImplementationSpecific
#   - host: dashboard.retail.adeptmind.net
#     http:
#       paths:
#       - backend:
#           service:
#             name: infra-dashboard-svc
#             port:
#               number: 9090
#         pathType: ImplementationSpecific
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: test.retail.adeptmind.net
    http:
      paths:
      - path: /
        backend:
          serviceName: infra-dashboard-svc
          servicePort: 9090
