apiVersion: v1
kind: Service
metadata:
  name: infra-dashboard-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: infra-dashboard-canary
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: app
---
apiVersion: v1
kind: Service
metadata:
  name: infra-dashboard-stable
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: app
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-dashboard-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - app.infra-dashboard.api.adeptmind.net
  http:
  - name: primary
    route:
    - destination:
        host: infra-dashboard-stable
      weight: 100
    - destination:
        host: infra-dashboard-canary
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: istio-rollout-gateway
spec:
 selector:
   istio: ingressgateway # use Istio default gateway implementation
 servers:
 - port:
     number: 80
     name: http
     protocol: HTTP
   hosts:
   - "app.infra-dashboard.api.adeptmind.net"
---
apiVersion: v1
kind: Service
metadata:
  name: infra-dashboard-lb
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: app
